# Generated by Django 3.1.7 on 2021-03-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dat',
            new_name='date',
        ),
    ]
